$font = FiraCode Nerd Font

general {
    hide_cursor = false
}

auth {
    fingerprint {
       enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}

animations {
    enabled = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $FPRINTPROMPT
    font_size = 14
    font_family = $font
    font_color = rgb(200, 200, 200)

    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT[en,ru]
    font_size = 18
    onclick = hyprctl switchxkblayout all next

    position = 200, -20
    halign = center
    valign = center
}
