alias l='ls -lah --color=auto'
alias sourcezsh='source ~/.zshrc'
alias v='nvim'
alias ff='fastfetch'
alias lg='lazygit'
alias y='yazi'
alias ta='tmux attach'
alias t='tmux'
alias tk='tmux kill-server'
alias tl='tmux ls'
alias chd='chezmoi cd'
alias chra='chezmoi re-add'
alias cha='chezmoi add'

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ip='ip --color=auto'

alias cat='bat --style=plain --paging=never'
alias ccat='\cat'               # original cat command
