decoration {
  rounding = 10

  shadow {
    enabled = false
  }

  blur {
    enabled = false
  }
}

#layerrule = blur on, match:namespace waybar
#layerrule = ignore_alpha 0.3, match:namespace waybar
