exec-once = systemctl --user start hyprpolkitagent
exec-once = mako
exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle
exec-once = bash -c '[ -x /usr/lib/pam_kwallet_init ] && /usr/lib/pam_kwallet_init'
exec-once = rm -f /tmp/wob_pipe && mkfifo /tmp/wob_pipe && tail -f /tmp/wob_pipe | wob -c ~/.config/wob/wob.ini
exec-once = ~/.config/hypr/scripts/battery-watch
