$mod = SUPER
$launcher = rofi

bind = $mod, T, exec, ghostty
bind = $mod, D, exec, $launcher -show run
bind = $mod, B, exec, brave
bind = $mod, Q, exec, kill -9 $(hyprctl activewindow -j | jq '.pid')
bind = $mod SHIFT, E, exit
bind = $mod, ESCAPE, exec, hyprlock

bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d

bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, L, movewindow, r
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, J, movewindow, d

bind = $mod, SPACE, exec, hyprctl switchxkblayout all next

bind = $mod SHIFT, V, togglefloating
bind = $mod, V, exec, rofi -modi clipboard:~/.config/hypr/scripts/cliphist-rofi-img -show clipboard -show-icons

bind = $mod, F, fullscreen

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Volume (Fn keys)
bindel = , XF86AudioRaiseVolume, exec, /home/pa2/.config/hypr/scripts/vol-change +5
bindel = , XF86AudioLowerVolume, exec, /home/pa2/.config/hypr/scripts/vol-change -5
bindl  = , XF86AudioMute, exec, /home/pa2/.config/hypr/scripts/vol-change mute

# Brightness (Fn keys)
bindel = , XF86MonBrightnessUp,   exec, /home/pa2/.config/hypr/scripts/bright-change +5%
bindel = , XF86MonBrightnessDown, exec, /home/pa2/.config/hypr/scripts/bright-change 5%-

# Lid close → lock + suspend
bindl = , switch:Lid Switch, exec, loginctl lock-session && systemctl suspend
